default:
  # Basic runtime config
  dt_cores:             78 # Number of cores that data.table is going to use
  dt_verbose:           FALSE # Should data.table be verbose
  mcl_bin:              "mcl" # Where is the MCL binary
  mcl_inflation_min:    2.2 # Minimum MCL inflation value
  mcl_inflation_max:    2.3 # Maximum MCL inflation value
  mcl_inflation_step:   0.1 # MCL inflation step
  mcl_jobs:             2 # How many simultaneous MCL jobs should be ran
  mcl_cores:            32 # How many cores MCL will use
  max_gc_jobs:          19 # How many simulatneous jobs are going to be used for the inflation values
  entropy_cores:        78 # Number of cores to calculate MCL cluster entropy (uses a lot of RAM, 32 for bigmems)
  das_refinement_cores: 64
  # Files
  wd:                   "/scratch/antonio/unk_C_SC"
  graph_lib:            "/scratch/antonio/unk_C_SC/component_inference/graph_lib.R"
  cl_cat:               "/scratch/antonio/unk_C_SC/data/cl_ids_categ_10M.tsv"
  cl_comp:              "/scratch/antonio/unk_C_SC/data/cl_completion_10M.tsv"
  p_clan:               "/bioinf/projects/megx/UNKNOWNS/2017_11/Pfam_annotation/pfam_files/Pfam-A.clans.tsv.gz"
  p_doms:               "/scratch/antonio/unk_C_SC/data/da_reduced_original_names_fix_10M.tsv"
  hhblits_results:      "/scratch/antonio/unk_C_SC/data/k_hhblits_10M.tsv"
  # Files with results tht can be loaded to skip time consuming steps, leave it empty to recalculate them
  k_g_mcl_list:         "/scratch/antonio/unk_C_SC/2019-02-21_070814/k_g_mcl_list_2019-02-21_070814.Rda"
  k_gc:                 "/scratch/antonio/unk_C_SC/2019-02-21_074546/k_gc_2019-02-21_074546.Rda"
  k_gc_da_sg:           "/scratch/antonio/unk_C_SC/2019-02-21-090232/k_gc_da_sg_2019-02-21-090232.Rda"
  k_gc_entropy:         "/scratch/antonio/unk_C_SC/2019-02-21-121744/k_gc_entropy_2019-02-21-121744.Rda"
  da_dist:              "/scratch/antonio/unk_C_SC/2019-02-21-141629/da_dist_2019-02-21-141629.tsv"
  k_das_refinement:     ""
